[package]
name = "darkbio-crypto-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
darkbio-crypto = { version="0.11.8", features = ["rand", "hkdf", "argon2", "cose"] }
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
